openapi: 3.0.3
info:
  title: Catalog Management Micro Service
  description: 'Service implementing the persistence of e-services'
  version: 0.0.1
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  termsOfService: 'http://swagger.io/terms/'
  x-api-id: an x-api-id
  x-summary: an x-summary
servers:
  #  - url: https://gateway.interop.pdnd.dev/pdnd-interop-uservice-catalog-management/0.0.1
  - url: /pdnd-interop-uservice-catalog-management/0.0.1
    description: This service is eservice manager
security:
  - bearerAuth: [ ]
tags:
  - name: e_service
    description: Everything about your E-service
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /eservices:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - e_service
      summary: Add a new e-service
      operationId: createEService
      requestBody:
        description: A E-Service seed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EServiceSeed'
        required: true
      responses:
        "200":
          description: EService created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EService'
        "400":
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - e_service
      summary: Retrieve a list of e-service
      operationId: getEServices
      parameters:
        - in: query
          name: producerId
          schema:
            type: string
        - in: query
          name: consumerId
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: string
            enum: [ draft, active, suspended ]
      responses:
        "200":
          description: A list of EService
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EServices'
  /eservice/{eServiceId}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - e_service
      summary: Get an e-service
      operationId: getEService
      parameters:
        - name: eServiceId
          in: path
          description: the eservice id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: EService retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EService'
        '404':
          description: EService not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /eservice/{eServiceId}/descriptors/{descriptorId}:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - e_service
      summary: Publish a new descriptors
      operationId: publishDescriptor
      parameters:
        - name: eServiceId
          in: path
          description: the eservice id
          required: true
          schema:
            type: string
        - name: descriptorId
          in: path
          description: the descriptor Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: EService Descriptor published
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EService'
        "400":
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /eservice/{eServiceId}/descriptors/{descriptorId}/interface:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - e_service
      summary: Add a new e-service inteface
      operationId: createEServiceInterface
      parameters:
        - name: eServiceId
          in: path
          description: the eservice id
          required: true
          schema:
            type: string
        - name: descriptorId
          in: path
          description: the descriptor Id
          required: true
          schema:
            type: string
      requestBody:
        description: A E-Service seed
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - description
                - technology
                - idl
              properties:
                description:
                  type: string
                technology:
                  type: string
                  enum: [ 'REST', 'SOAP' ]
                idl:
                  type: string
                  format: binary
            encoding:
              idl:
                contentType: application/yaml, application/xml
        required: true
      responses:
        "200":
          description: EService Interface created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EService'
        "400":
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /eservice/{eServiceId}/descriptors/{descriptorId}/documents/{documentId}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - e_service
      summary: Get an e-service document
      operationId: getEServiceDocument
      parameters:
        - name: eServiceId
          in: path
          description: the eservice id
          required: true
          schema:
            type: string
        - name: descriptorId
          in: path
          description: the descriptor Id
          required: true
          schema:
            type: string
        - name: documentId
          in: path
          description: the document id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: EService document retrieved
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: EService not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    EServiceSeed:
      type: object
      required:
        - name
        - description
        - audience
        - attributes
        - voucherLifespan
      properties:
        name:
          type: string
        description:
          type: string
        audience:
          type: array
          items:
            type: string
        voucherLifespan:
          type: integer
          format: int32
        attributes:
          $ref: '#/components/schemas/Attributes'
    EService:
      type: object
      required:
        - id
        - producerId
        - name
        - description
        - audience
        - voucherLifespan
        - attributes
        - descriptors
      properties:
        id:
          type: string
          format: uuid
        producerId:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        audience:
          type: array
          items:
            type: string
        technology:
          type: string
        voucherLifespan:
          type: integer
          format: int32
        attributes:
          $ref: '#/components/schemas/Attributes'
        descriptors:
          type: array
          items:
            $ref: '#/components/schemas/EServiceDescriptor'
    EServiceDoc:
      type: object
      required:
        - id
        - name
        - contentType
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        contentType:
          type: string
    EServiceDescriptor:
      type: object
      required:
        - id
        - version
        - docs
        - status
        - creationDate
      properties:
        id:
          type: string
          format: uuid
        version:
          type: string
        description:
          type: string
        docs:
          type: array
          items:
            $ref: '#/components/schemas/EServiceDoc'
        status:
          type: string
          enum: [ 'draft', 'published','deprecated','archived' ]
    Attribute:
      type: object
      properties:
        simple:
          type: string
        group:
          type: array
          items:
            type: string
    Attributes:
      properties:
        certified:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
        declared:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
        verified:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
      required:
        - certified
        - declared
        - verified
    EServices:
      type: array
      items:
        $ref: '#/components/schemas/EService'
    Problem:
      properties:
        detail:
          description:
            A human readable explanation specific to this occurrence of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
        status:
          description:
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description:
            A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: '^[ -~]{0,64}$'
          type: string
      additionalProperties: false
      required:
        - status
        - title
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT