/**
 * Catalog Management Micro Service
 * Service implementing the persistence of e-services
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.catalogmanagement.client.model




sealed trait EServiceDescriptorStatusEnum

case object DRAFT extends EServiceDescriptorStatusEnum
case object PUBLISHED extends EServiceDescriptorStatusEnum
case object DEPRECATED extends EServiceDescriptorStatusEnum
case object SUSPENDED extends EServiceDescriptorStatusEnum
case object ARCHIVED extends EServiceDescriptorStatusEnum

