/**
 * Catalog Management Micro Service
 * Service implementing the persistence of e-services
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.catalogmanagement.client.model

import it.pagopa.pdnd.interop.uservice.catalogmanagement.client.invoker.ApiModel

case class UpdateEServiceDescriptorSeed (
  description: Option[String] = None,
  status: UpdateEServiceDescriptorSeedEnums.Status,
  audience: Seq[String],
  voucherLifespan: Int
) extends ApiModel

object UpdateEServiceDescriptorSeedEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Draft = Value("draft")
    val Published = Value("published")
    val Deprecated = Value("deprecated")
    val Suspended = Value("suspended")
    val Archived = Value("archived")
  }

}
